- src/pysweepme/EmptyDeviceClass.py
- src/pysweepme/FolderManager.py
- src/pysweepme/UserInterface.py
`import pysweepme`
should not instantiate the FolderManager already, so that the application still has the possibility to do adjustments like setting an instance ID (in case of using multiple instances of SweepMe! / pysweepme
> Only get FolderManager Instance when needed, but not when importing

- src/pysweepme/FolderManager.py
Add the ability to run multiple application instances at the same time. Therefore,
- add a suffix with the process ID to certain folders / files like temp or debug.log
- add the option to create a FolderManager Instance that corresponds to another process (to get the other's instance folders for cleanup)
> Multi instance abilities

- src/pysweepme/FolderManager.py
Add PythonScripts folder to FolderManager, so that the folder can be created upon starting the application.
The creation of folders itself will create missing folders recursively now.
> Add PythonScripts folder to FolderManager

- src/pysweepme/PortManager.py
For the multiinstance feature to work, the FolderManager must not be initialized before the whole pysweepme package has been imported.
> Fix instantiation of FolderManager

- src/pysweepme/FolderManager.py
For new DCs / Modules, the FolderManager tries to find libs in the libraries/libs_<architecture> and libraries/libs_common folder now. The folders have been moved into a separate libraries folder, so that the main directory does not get cluttered so much. Also, there is a libs_common folder now, where developers can put (pure *.py) libs that do not have architecture differences (like libraries written on their own just for this driver).
> Look in libraries folder for libs

- src/pysweepme/FolderManager.py
Libraries folder is used by newer SweepMe! versions and will have incompatible binary code which would lead to load errors. Therefore, the libraries folder is excluded form being added to the PATH.
> Do not add libraries folder to path

- .github/check_version_uniqueness.py
Directive to exclude whole rulesets seems to be no longer supported.
> Explicitly specify excluded rules

- src/pysweepme/EmptyDeviceClass.py
reach() is a [sequencer function](https://wiki.sweep-me.net/wiki/Sequencer_procedure) and thus should be defined in the EmptyDevice class. Application logic that needs to check if reach was overridden by an instrument driver, should use appropriate code (i.e. check the `__dict__` of the cls)
> Reach handling

- src/pysweepme/Ports.py
- src/pysweepme/__init__.py
Clearing the port can reset devices under rare circumstances. Therefore, the clearing is moved to a separate function that should be called when needed.
> Move port clearing to separate function

- src/pysweepme/ErrorMessage.py
- src/pysweepme/FolderManager.py
- src/pysweepme/__init__.py
- Only add folders to system PATH environment variable when they contain dll's (PATH cannot exceed 32767 characters)
- add type hints to debug / error functions
> Only add folders to system PATH environment variable when they contain dll's

- src/pysweepme/UserInterface.py
- src/pysweepme/__init__.py
Applications can now register a custom function that shall handle calls to pysweepme's User Interface functions.
It is no longer required to overwrite (monkey patch) the pysweepme functions, which was sensitive to import order.
> Add option for applications to register their own UI function

- pyproject.toml
- src/pysweepme/Config.py
- src/pysweepme/pysweepme_types.py
- tests/test_config.py
- By default, pathlib.Path() is used for file IO
- Applications can register an alternative class that shall handle file IO, e.g. if more control is required regarding locking of files and access of files from different instances of applications
> Enable an application to define an alternative way for file IO

- src/pysweepme/EmptyDeviceClass.py
- src/pysweepme/__init__.py
- src/pysweepme/_utils.py
- tests/test_utils.py
- Removed following semantic functions from EmptyDevice:
- trigger (use measure instead)
- process (use process_data to process something before call, or use finish to do cleanup etc.)
- Other deprecated functions of EmptyDevice (because of naming conventions) will trigger a warning message.
- A deprecation warning will also show, where from the deprecated function was called
> Remove trigger and process and mark deprecated functions as such

- .github/workflows/publish.yml
- LICENSE.md
- README.md
- src/pysweepme/DeviceManager.py
- src/pysweepme/EmptyDeviceClass.py
- tests/test_device_manager.py
- When using the port manager, automatically clear port in connect()
- DeviceManager has new functions to obtain only the driver class (no instance) or the module of the driver
- Updated Readme
- No manually maintained Changelog anymore. Changes are generated from pull requests automatically
> Clear port after connecting to an instrument

- src/pysweepme/EmptyDeviceClass.py
- src/pysweepme/PortManager.py
- src/pysweepme/Ports.py
- src/pysweepme/__init__.py
- clear() is called immediately after a port is opened by the Port Manager
- connect() of EmptyDevice does not do anything
- use `self.port_properties["clear"] = False` to disable running clear() on the port
> Clear port is performed before (and thus outside) the connect() function of a driver

- src/pysweepme/Ports.py
This change allows to retrieve informatione when retrieving identification information in the Port manager tool of SweepMe!. VID, PID and serial number could later be used to identify certain COM ports and only list relevant ones when using Find ports.
> Ports -> get_identification defined for COM ports

- .github/workflows/publish.yml
Old twine versions fail to upload to pypi, using the latest version fixes the issues
> Update build tools versions

- src/pysweepme/DeviceManager.py
- src/pysweepme/__init__.py
Previously, get_driver was obtaining a (new) port from the low-level Ports module every time it was called. This led to errors when the port was already opened, also when combining the same driver in a SweepMe! module and a CustomFunction Script using get_driver(). Now, the PortManager is used consistently.
> Use PortManager to obtain ports in get_driver()

- src/pysweepme/DeviceManager.py
- src/pysweepme/ErrorMessage.py
- src/pysweepme/__init__.py
Driver or other source files could break the error-handling when they contained non UTF-8 characters. An exception was thrown and a traceback was attempted to be printed, which however failed because the traceback was trying to read the invalid character as well, resulting in another exception.
With this PR, the traceback printing is monkey patched to skip reading a file if there was a UnicodeDecodeError beforehand.
> Improve error handling

- src/pysweepme/EmptyDeviceClass.py
- src/pysweepme/__init__.py
As an alternative to set/get_GUIparameters, a new way of exchanging parameters between the application and the driver has been introduced:
- update_gui_parameters: A function similar to the old set_GUIparameter, i.e. it will return the default GUI parameters for the driver, but in addition it accepts a dictionary with the current values defined in the GUI and the resulting "default" dictionary might depend on other fields in the GUI.
- apply_gui_parameters: A function similar to the old get_GUIparameter, i.e. it gets a dictionary with the GUI parameter values from the GUI. This function is however coupled to the update_gui_parameters and called more often than the old get_GUIparameter, which has the unfortunate side effect that the driver must account for incomplete or invalid input.
In …
> New handling of GUI parameters supporting dynamic GUI parameters

- src/pysweepme/EmptyDeviceClass.py
Switch to 1.5.7 shall not introduce breaking changes and therefore the deprecated functions will only be removed in 1.5.8
> Extend lifetime of deprecated functions

- .github/workflows/tox.yml
- tox.ini
- Don't use the console spinner when running tox, as the github actions clutter the log with a new line every second
- Also install the optional typed dependencies of pysweepme when running the checks
> Improve readability of tox output and add typed packages for ruff tests

- src/pysweepme/Ports.py
Don't close the port on error, as shutdown functions (unconfigure, deinitialize ...) might still need to send commands to the instrument. This was only present for COM ports.
> Don't close the port on error
